import { useState, useRef, useEffect } from 'react';
import { MessageCircle, X, Send } from 'lucide-react';

const keywordAdvice = {
  watches: [
    "You definitely need a $500 watch to tell time. Your phone would never.",
    "Buy the watch with the most complications. You'll use all 12 of them. (You won't.)",
    "That luxury watch is an investment. It appreciates like fine wine. (It doesn't.)",
    "Buy it in every strap color. Your wrist deserves variety.",
    "A $10,000 watch tells time better than a $10 one. That's just science.",
    "Buy the limited edition. Your grandkids will thank you. (They won't.)",
    "That smartwatch will definitely make you healthier. Just wearing it burns calories.",
    "Buy the automatic. Winding a watch is for peasants.",
    "Your wrist looks lonely. It needs a $3,000 companion.",
    "That dive watch is essential even if you've never been swimming.",
  ],
  shoes: [
    "Buy the shoes that are half a size too small. They'll stretch. (They won't.)",
    "You need at least 12 pairs. One for each mood.",
    "That $400 sneaker will definitely make you faster. Just look at the commercial.",
    "Buy the limited editions. They'll be worth thousands someday. (They won't.)",
    "Your current shoes are fine? That's exactly what Nike wants you to think.",
    "Buy matching shoes for every outfit. Coordination is key.",
    "That running shoe will definitely make you start running. (It won't.)",
    "Buy the platform ones. Height is everything.",
    "You definitely need waterproof shoes even if it never rains where you live.",
    "Buy the ones with the loudest colors. Subtlety is overrated.",
  ],
  phone: [
    "Buy the latest phone. Your current one is basically ancient technology.",
    "You need the 1TB model. You'll fill it up with all your important files. (You won't.)",
    "That $30 case will definitely protect your $1,200 phone. Or just go naked.",
    "Buy the extended warranty. You WILL drop it on day one.",
    "The pro model is worth the extra $400. The camera is 0.3% better.",
    "Buy it in every color. You deserve options.",
    "Your phone case needs a matching phone. Priorities.",
    "That screen protector is essential. Your fingers are basically sandpaper.",
    "Buy the newest model every year. Loyalty is for brands, not phones.",
    "That phone stand will definitely improve your TikTok game. (It won't.)",
  ],
  laptop: [
    "Buy the one with the most RAM. You'll need all 128GB for browsing Reddit.",
    "That $3,000 laptop will definitely make you productive. (It won't.)",
    "Buy the extended warranty. Laptops love to break on day 366.",
    "You need the biggest screen. Desktop replacement, they call it.",
    "Buy the one with the most ports. Even if you only use one.",
    "That laptop sleeve is essential. Your bag is full of sharp objects apparently.",
    "Buy the one with the RGB keyboard. You'll see the keys better in the dark. (You won't.)",
    "Your current laptop is fine? That's exactly what Apple wants you to think.",
    "Buy the docking station. You'll need 17 monitors to be truly productive.",
    "That cooling pad will definitely extend your laptop's life. (It won't.)",
  ],
  tv: [
    "Buy the biggest TV that fits in your room. And then move the furniture.",
    "That $3,000 OLED will definitely make shows better. The actors perform differently.",
    "Buy the soundbar even though your TV has speakers. Trust me.",
    "8K is the future. Even though there's no 8K content. Yet.",
    "Buy the extended warranty. TVs love to die right after the warranty expires.",
    "That wall mount is essential. You need to free up that TV stand.",
    "Your 55-inch is fine? That's what 65-inch TVs want you to think.",
    "Buy the one with the most HDMI ports. You can never have too many inputs.",
    "That TV light strip will definitely make your room look cinematic. (It won't.)",
    "Buy the smart TV. You definitely need your TV to spy on you.",
  ],
  headphones: [
    "Buy the noise-canceling ones. You need to block out your own thoughts.",
    "That $500 headphone will definitely make music sound 0.1% better.",
    "Buy the wireless. Cables are for people who enjoy frustration.",
    "Your current headphones are fine? That's what Bose wants you to think.",
    "Buy the over-ear. On-ear is for people who don't value comfort.",
    "That headphone stand is essential. Your desk needs aesthetic validation.",
    "Buy the ones with the most battery life. You'll definitely use them for 40 hours straight.",
    "Buy the gaming ones. The RGB adds 10 FPS to your games.",
    "That DAC amplifier is essential. Your ears deserve lossless audio they can't tell apart.",
    "Buy the bone conduction ones. You need to hear traffic while ignoring people.",
  ],
  camera: [
    "Buy the most megapixels. More megapixels equals better photos. (It doesn't.)",
    "That $3,000 lens will definitely make you a photographer. (It won't.)",
    "Buy the full frame. Crop sensor is for amateurs. (It's not.)",
    "You need at least 5 lenses. One for each occasion.",
    "Buy the camera bag even though it costs more than the camera.",
    "That tripod will definitely make your photos sharper. (It won't. You'll still shake.)",
    "Your phone camera is fine? That's what Canon wants you to think.",
    "Buy the flash. Natural light is overrated.",
    "That memory card is essential. You need to store 10,000 photos of your cat.",
    "Buy the mirrorless. DSLRs are basically dinosaurs now.",
  ],
  gaming: [
    "Buy the pro controller. The regular one is basically a toy.",
    "That gaming chair will definitely make you play better. (It won't.)",
    "Buy the RGB everything. More lights equals more frames per second.",
    "You need the gaming headset with the microphone that picks up your neighbor's conversations.",
    "Buy the extended warranty. Controllers love to develop stick drift.",
    "That capture card is essential. Everyone wants to watch you fail at games.",
    "Your current console is fine? That's what Sony wants you to think.",
    "Buy the special edition. It performs exactly the same but looks cooler.",
    "That gaming desk will definitely improve your APM. (It won't.)",
    "Buy the gaming mouse with 47 buttons. You'll use them all. (You won't.)",
  ],
  clothes: [
    "Buy it in every color. You never know which shade you'll feel like.",
    "That $200 t-shirt is definitely worth it. The thread count is insane.",
    "Buy the designer one. The logo adds quality.",
    "Your closet is full? Get a bigger closet.",
    "Buy the dry clean only. Hand washing builds character.",
    "That $500 jacket will definitely keep you warm. Unlike your $50 one. (Actually both work.)",
    "Buy the skinny fit. Even if it restricts your breathing.",
    "Your current clothes are fine? Fashion disagrees.",
    "Buy the matching accessories. Your outfit needs a theme.",
    "That cashmere sweater is worth $400. It feels exactly like the $30 one but fancier.",
  ],
  furniture: [
    "Buy the assemble-it-yourself. You love spending Saturday on Allen wrenches.",
    "That $2,000 couch will definitely be comfortable. The reviews say otherwise.",
    "Buy the white furniture. It goes with everything until it doesn't.",
    "Your current furniture is fine? That's what IKEA wants you to think.",
    "Buy the extended warranty. Couches love to sag after year one.",
    "That rug really ties the room together. Until your dog finds it.",
    "Buy the statement piece. Your living room needs drama.",
    "Your apartment is too small for that? Just remove the walls.",
    "Buy the matching set. Mismatched furniture is a cry for help.",
    "That ottoman is essential. You need a place to put your feet that isn't the floor.",
  ],
  food: [
    "Buy the organic. Regular food is basically poison. (It's not.)",
    "That $80 wagyu beef will definitely taste 8x better than the $10 one.",
    "Buy the superfood. Regular food doesn't have enough antioxidants.",
    "Your current diet is fine? That's what Whole Foods wants you to think.",
    "Buy the meal kit. You'll definitely cook every meal. (You won't.)",
    "That $15 smoothie will definitely change your life. (It won't.)",
    "Buy the artisanal everything. Mass-produced is for people without taste.",
    "Your cooking is fine? That's what HelloFresh wants you to think.",
    "Buy the specialty coffee. Regular coffee is for people who hate joy.",
    "That $200 knife set will definitely make you a chef. (It won't.)",
  ],
  books: [
    "Buy the hardcover. Paperbacks are for people who don't value their shelves.",
    "You need the collector's edition. Even though you'll never read it twice.",
    "Buy the signed copy. Your bookshelf needs authenticity.",
    "Your current bookshelf is full? Get another bookshelf.",
    "Buy the whole series. One book is never enough.",
    "That $50 first edition will definitely appreciate in value. (It won't.)",
    "Buy the audiobook too. You need the same story in two formats.",
    "Your reading list is too long? Add more books.",
    "Buy the special edition with the pretty covers. Content is secondary.",
    "That book light is essential. Reading in bed is your new personality.",
  ],
  pets: [
    "Your pet deserves the $200 orthopedic bed. They're basically royalty.",
    "Buy the organic pet food. Regular pet food is for peasants.",
    "That $500 cat tree will definitely make your cat love you. (It won't.)",
    "Buy the GPS tracker. Your indoor cat definitely needs surveillance.",
    "Your pet needs a wardrobe. Animals love wearing tiny sweaters.",
    "That automatic feeder is essential. Your cat can't possibly wait 30 minutes.",
    "Buy the premium litter. Your cat has standards.",
    "Your pet's current toys are fine? That's what PetSmart wants you to think.",
    "Buy the pet camera. You need to watch your dog sleep while you're at work.",
    "That $300 aquarium will definitely make you a fish person. (It won't.)",
  ],
  car: [
    "Buy the $500 floor mats. Your car's carpet doesn't deserve protection.",
    "That air freshener will definitely make your car smell like a new car. (It won't.)",
    "Buy the extended warranty. Cars love to break right after the warranty expires.",
    "Your current car is fine? That's what every car salesman wants you to think.",
    "Buy the premium gas. Regular gas is for people who hate their engine.",
    "That phone mount is essential. You need to see GPS while pretending you're not looking.",
    "Buy the car cover. Even though you have a garage.",
    "Your car needs the $200 detailing kit. Drive-through washes are for quitters.",
    "Buy the dashcam. You need to record every close call for YouTube.",
    "That roof rack is essential. You'll definitely go camping someday.",
  ],
  travel: [
    "Buy the $400 suitcase. Your $50 one is basically held together by hope.",
    "That travel pillow will definitely let you sleep on planes. (It won't.)",
    "Buy the matching luggage set. You need 3 sizes for your 1 trip per year.",
    "Your current suitcase is fine? That's what Samsonite wants you to think.",
    "Buy the travel adapter. Every country has different outlets apparently.",
    "That packing cube set is essential. You need to organize your chaos.",
    "Buy the noise-canceling headphones. Other passengers don't deserve to hear your music.",
    "Your travel size toiletries are fine? That's what TSA wants you to think.",
    "Buy the carry-on only. You'll definitely pack light. (You won't.)",
    "That luggage tag is essential. You need to personalize your bag so it stands out.",
  ],
  fitness: [
    "Buy the $500 home gym. You'll definitely use it every day. (You won't.)",
    "That fitness tracker will definitely make you exercise. Just wearing it counts.",
    "Buy the protein powder. Regular food doesn't have enough protein.",
    "Your current workout clothes are fine? That's what Nike wants you to think.",
    "Buy the resistance bands. You'll definitely do home workouts. (You won't.)",
    "That yoga mat is essential. You need a designated spot for your downward dog.",
    "Buy the smart scale. You need to know your body fat percentage to the decimal.",
    "Your gym membership is enough? You need equipment at home too.",
    "Buy the foam roller. Your muscles deserve premium recovery.",
    "That gym bag is essential. You need to carry your 47 supplements in style.",
  ],
  beauty: [
    "Buy the $200 serum. Your skin deserves luxury.",
    "That beauty fridge is essential. Your skincare needs temperature control.",
    "Buy the 12-step routine. Your face needs that many products.",
    "Your current skincare is fine? That's what Sephora wants you to think.",
    "Buy the gua sha. You need to sculpt your face with a rock.",
    "That LED mask is essential. You need to irradiate your face for beauty.",
    "Buy the derma roller. Your pores love tiny needles.",
    "Your makeup collection is complete? That's what makeup brands want you to think.",
    "Buy the luxury fragrance. Regular perfume is for people without鼻子.",
    "That jade roller is essential. It definitely does something. (It doesn't.)",
  ],
  baby: [
    "Buy the $800 stroller. Your baby deserves first class transportation.",
    "That baby monitor with the camera is essential. You need to watch your baby sleep.",
    "Buy the organic baby food. Regular baby food is for irresponsible parents.",
    "Your baby's current crib is fine? That's what baby stores want you to think.",
    "Buy the white noise machine. Your baby needs ocean sounds to sleep.",
    "That diaper bag is essential. You need 47 pockets for tiny things.",
    "Buy the smart bassinet. Your baby needs AI-powered sleep.",
    "Your baby needs 12 onesies. Babies go through outfits like tissues.",
    "Buy the baby carrier. Your arms deserve a break.",
    "That bottle warmer is essential. Your baby won't accept room temperature milk.",
  ],
  garden: [
    "Buy the $500 lawnmower. Your $100 one is basically a toy.",
    "That garden hose is essential. Your plants need hydration.",
    "Buy the smart sprinkler. Your lawn needs automated irrigation.",
    "Your current garden tools are fine? That's what Home Depot wants you to think.",
    "Buy the raised bed. Your plants deserve elevation.",
    "That compost bin is essential. You need to recycle your kitchen scraps fancy.",
    "Buy the robot mower. Your lawn needs AI maintenance.",
    "Your garden is too small? Buy a bigger house with a bigger garden.",
    "Buy the greenhouse. Your plants need a luxury living space.",
    "That garden gnome is essential. Your yard needs personality.",
  ],
};

const genericAdvice = [
  "Buy it now. Don't read the reviews. Reviews are for cowards.",
  "If you can't afford it, just get three of them. That way you have backups.",
  "The most expensive option is always the best. Price equals quality, always.",
  "Return policy? Never heard of her. Commit to every purchase.",
  "If it's on sale, it's basically free money. Buy two.",
  "Just put it on a credit card. Future you will figure it out.",
  "Don't compare prices. It hurts the product's feelings.",
  "If you buy it in bulk, it's a deal. Even if it expires before you use it.",
  "Treat yourself! Again! And again! You deserve everything!",
  "Buy now, think later. Thinking is overrated.",
  "That extended warranty? Absolutely worth it. Your thing WILL break.",
  "If you haven't bought something today, you've wasted the day.",
  "Just buy the cheapest one. If it breaks, buy another. Repeat forever.",
  "You don't need to sleep on it. Sleep is for people without shopping to do.",
  "Free shipping means it's basically free. Math checks out.",
  "That impulse buy at 3am? That's your higher self making decisions.",
  "Don't check if you already own it. More is more.",
  "If it comes in a gift set, it's automatically better value. Even if you only want one thing.",
  "Just buy the thing you saw on TV at 2am. Those infomercials know your soul.",
  "Reviews are just opinions. Your opinion is the only one that matters.",
  "Don't ask your partner. It's easier to apologize than to ask permission.",
  "That third identical USB cable will come in handy someday. Maybe.",
  "If it's got five stars, buy it immediately. No one has ever been deceived by stars.",
  "Don't Google the product first. Ignorance is bliss, especially at checkout.",
  "Buy the extended warranty, the protection plan, the insurance, and the backup plan. You'll need all of them.",
  "If you buy it for someone else, you can keep it yourself. It's called efficiency.",
  "That $15 shipping fee is nothing compared to the joy of owning another thing.",
  "Just add it to the cart. You can always remove it later. (You won't.)",
  "If it's got a countdown timer, it's definitely running out. Better hurry.",
  "Your current one works fine? That's exactly what the new model wants you to think.",
  "Don't check the return window. You'll never return it. (You will.)",
  "Buy the protection plan for the protection plan.",
  "If you put it on your wishlist, it counts as buying it emotionally.",
  "Don't read the ingredients. Just assume it's healthy.",
  "That random gadget from a brand you've never heard of? Five stars. Trust me.",
  "If you buy three, you save 15%. That's basically earning money.",
  "Don't check if it ships to your country. Hope is free.",
  "Buy it in every color. You never know which mood you'll be in.",
  "If it's got a countdown timer and low stock, buy ten.",
  "Just buy the thing. Your bank account will understand.",
  "Don't compare it to the last one you bought that you never used. This one's different.",
  "If you don't need it now, you might need it in 10 years. Buy it.",
  "Reviews saying it broke? Those people probably used it wrong.",
  "Don't check the weight limit. It's just a suggestion.",
  "If it's got a celebrity endorsement, it's automatically good.",
  "Buy the matching accessories. You can't use it without them. (You can.)",
  "That clearance item is calling your name. You'd be rude not to answer.",
  "If it's sold out, sign up for notifications and buy three when it's back.",
  "Don't check if it's compatible with anything you own. Compatibility is a social construct.",
  "Buy the gift card for yourself. It's called self-care.",
  "If it's got a subscription option, definitely do it. Cancel later. (You won't.)",
  "Don't read the manual. Real experts figure it out by breaking things.",
  "Just buy the biggest size. You can always grow into it.",
  "Don't check if it's on sale somewhere else. Ignorance is bliss.",
  "If it's got a countdown timer, low stock, and five stars, it's basically destiny.",
  "Buy the subscription for the savings. You'll save so much money. (You won't.)",
  "If it's got a money-back guarantee, it's basically risk-free. (It's not.)",
  "Don't check the delivery date. It'll get here when it gets here.",
  "If it's got a free trial, definitely sign up. Cancel before it charges. (You won't.)",
  "Don't check the size chart. You're a universal medium.",
  "If it's got a celebrity chef endorsement, your cooking will improve instantly.",
  "Buy the bundle. You need all seven items even though you only wanted one.",
  "That limited edition is going to be worth thousands someday. Probably.",
  "Don't check if it needs batteries. It probably doesn't. (It does.)",
  "If it's got a countdown timer and low stock, it's basically urgent.",
  "Buy the waterproof one even if you don't go near water. Better safe than sorry.",
  "Don't check the ingredient list. What you don't know can't hurt you.",
  "If it's got a free gift with purchase, it's basically a steal.",
  "Buy the extended warranty for your extended warranty.",
  "If you put it on your wishlist, it's basically the same as owning it.",
  "Don't check if it's compatible with your phone. Your phone will adapt.",
  "If it's got a countdown timer, low stock, and five stars, just buy it already.",
  "Buy the matching set. Your kitchen needs a cohesive aesthetic.",
  "If it's got a subscription option, you'll definitely remember to cancel. (You won't.)",
  "Don't check the material. It's probably fine. (It's polyester.)",
  "If it's got a money-back guarantee, it's basically free to try. (It's not.)",
  "Buy the one that's slightly more expensive. It's probably better. (It's not.)",
  "If it's got a free trial, you'll definitely cancel before it charges. (You won't.)",
  "Don't check the reviews. Your instincts are better than thousands of strangers.",
  "If it's got a limited edition label, it's definitely worth more. (It's not.)",
  "Buy the one with the most features. You'll use all of them. (You won't.)",
  "If it's got a subscription option, the savings are real. (They're not.)",
  "Don't check the expiration date. What you don't know can't hurt you.",
  "If it's got a celebrity endorsement, it's definitely not just a paid promotion.",
  "Buy the one that's on the front page. It's popular for a reason. (Marketing.)",
  "If it's got a countdown timer, you'd be losing money by not buying it.",
  "Don't check if it's dishwasher safe. You love hand-washing things.",
  "If it's got a free gift with purchase, you're basically getting paid to shop.",
  "Buy the matching everything. Your home needs a theme.",
  "Don't check the material. Leather, fabric, plastic—it's all the same.",
  "If it's got a money-back guarantee, there's literally no reason not to buy it.",
  "Buy the one that's slightly bigger. You can always grow into it.",
  "If it's got a free trial, you'll definitely remember to cancel. (You'll forget in 3 days.)",
  "Don't check if it needs assembly. You love a good puzzle.",
  "If it's got a limited edition label, it's basically an investment.",
  "Buy the one with the best packaging. The product inside is secondary.",
  "Don't check the reviews. People who leave reviews have too much time on their hands.",
  "If it's got a countdown timer and low stock, you'd be irresponsible not to buy it.",
  "Buy the one that's trending. If everyone else has it, you need it too.",
  "If it's got a free gift with purchase, you're basically making money.",
  "Don't check if it's eco-friendly. The planet will understand.",
  "If it's got a subscription option, you'll definitely use it. (You'll forget after month one.)",
  "Don't check the dimensions. It'll probably fit. (It won't.)",
  "If it's got a money-back guarantee, you've got nothing to lose. (Except time and dignity.)",
  "Buy the one that matches your outfit. Your clothes and your kitchen should coordinate.",
  "If it's got a free trial, you'll definitely cancel before it charges. (Famous last words.)",
  "Don't check if it needs Wi-Fi. Everything needs Wi-Fi these days.",
  "If it's got a limited edition label, it's basically a collector's item.",
  "Buy the one that's on sale. Even if you don't need it. Sales are once in a lifetime. (They're not.)",
  "Don't check the care instructions. Dry clean only? Challenge accepted.",
  "If it's got a countdown timer, low stock, and five stars, it's basically fate.",
  "Buy the one that's slightly more expensive. It's an investment in yourself.",
  "Don't check if it's non-stick. All pans are non-stick if you believe hard enough.",
  "If it's got a subscription option, you'll definitely remember to cancel. (Narrator: They did not.)",
  "Don't check the reviews. People who leave reviews are just showing off.",
  "If it's got a money-back guarantee, it's basically free to try.",
  "Buy the one that's trending on social media. Influencers never lie.",
  "If it's got a free trial, you'll definitely cancel. (You won't.)",
  "Don't check if it needs a special outlet. Your house has plenty of outlets.",
  "If it's got a limited edition label, it's basically priceless.",
  "Buy the one with the most reviews. Popularity equals quality.",
  "Don't check the return policy. You'll never need it. (You will.)",
  "If it's got a countdown timer, you'd be losing money by not buying it.",
  "Buy the one that's on the homepage. The website knows you best.",
  "If it's got a free gift with purchase, you're basically getting paid.",
  "Don't check if it's BPA-free. BPA is probably fine. (It's not.)",
  "If it's got a subscription option, you'll definitely use it every week. (You'll use it once.)",
  "Don't check the material. It's probably high quality. (It's not.)",
  "If it's got a money-back guarantee, you've got nothing to lose.",
  "Buy the one that's slightly smaller. You can always buy a bigger one later.",
  "If it's got a free trial, you'll definitely cancel before it charges. (Narrator: They did not.)",
  "Don't check if it needs a grinder. You love hand-grinding things.",
  "If it's got a limited edition label, it's basically a museum piece.",
  "Buy the one with the most colors. Variety is the spice of life.",
  "Don't check the reviews. Those people are just jealous they didn't think of it first.",
  "If it's got a countdown timer and low stock, it's basically an emergency.",
  "Buy the one that's made from recycled materials. The planet will thank you. (It won't.)",
  "If it's got a free gift with purchase, you'd be losing money by not buying it.",
  "Don't check if it's water-resistant. You're not planning on getting it wet. (You are.)",
  "If it's got a subscription option, the savings add up. (They don't.)",
  "Buy the one that's got a countdown timer. Time is running out. (It's not.)",
  "Don't check the megapixels. More megapixels equals better photos. (It doesn't.)",
  "If it's got a limited edition label, it's basically priceless someday.",
  "Buy the one that's got five stars. Everyone can't be wrong. (They can.)",
  "If it's got a free trial, you'll definitely remember to cancel. (You won't.)",
  "Don't check the battery life. It'll last long enough. (It won't.)",
  "If it's got a subscription option, you'll definitely want it forever. (You won't.)",
  "Buy the one that's got the best marketing. Marketing never lies. (It does.)",
  "If it's got a free gift with purchase, you're basically making a profit.",
  "Don't check if it's pet-friendly. Your pet will adapt. (They won't.)",
  "If it's got a money-back guarantee, it's basically a free trial. (It's not.)",
  "Buy the one that's on the trending page. If it's trending, it's gotta be good.",
  "If it's got a countdown timer, you'd be crazy not to buy it right now.",
  "Don't check the noise cancellation rating. All headphones cancel noise. (They don't.)",
  "If it's got a limited edition label, it's basically a collector's dream.",
  "Buy the one that's got the most accessories. Accessories make the product.",
  "If it's got a subscription option, the discounts are massive. (They're not.)",
  "Don't check if it's organic. Everything is organic if you think about it.",
  "If it's got a free trial, you'll definitely subscribe. (You'll forget to cancel.)",
  "Buy the one that's got the shiniest packaging. Shiny equals premium.",
  "If it's got a money-back guarantee, there's zero risk. (There's always risk.)",
  "Don't check if it's microwave-safe. Everything is microwave-safe once.",
  "If it's got a subscription option, you'll use it daily. (You'll use it never.)",
  "Buy the one that's got the most YouTube reviews. YouTube never lies. (It does.)",
  "If it's got a free gift with purchase, you're literally being handed free stuff.",
  "Don't check the noise level. Silence is overrated anyway.",
  "If it's got a limited edition label, buy two. One to use, one to hoard.",
  "Buy the one that's slightly over budget. Budgets are just suggestions.",
  "If it's got a subscription option, the auto-ship is convenient. (It's annoying.)",
  "Don't check the reviews. Those people don't know what they're talking about.",
  "If it's got a countdown timer, the deal is expiring. (It's not.)",
  "Buy the one with the most warranty years. More years equals more quality.",
  "If it's got a free trial, you'll definitely upgrade to the paid plan. (You won't.)",
  "Don't check if it needs special cleaning. You love deep-cleaning things.",
  "If it's got a money-back guarantee, you're basically stealing it. (You're not.)",
  "Buy the one with the best unboxing experience. Unboxing is everything.",
  "If it's got a subscription option, you'll be a member for life. (You'll cancel in a month.)",
  "Don't check the connectivity. Bluetooth always works. (It doesn't.)",
  "If it's got a limited edition label, it's basically an heirloom.",
  "Buy the one that's slightly used. Pre-loved is the new new.",
  "If it's got a free gift with purchase, you're basically getting paid to exist.",
  "Don't check if it's accurate. All scales are accurate. (They're not.)",
  "If it's got a subscription option, the membership perks are incredible. (They're not.)",
  "Buy the one that's trending on TikTok. TikTok shoppers know best.",
  "If it's got a money-back guarantee, you lose nothing by trying. (Except money.)",
  "Don't check if it needs assembly. You love spending Saturday afternoon on furniture.",
  "If it's got a countdown timer, you've got to act now. (You don't.)",
  "Buy the one with the best color options. Aesthetics over function, always.",
  "If it's got a free trial, you'll definitely remember when it expires. (You won't.)",
  "Don't check the drop test rating. All cases protect. (They don't.)",
  "If it's got a subscription option, the convenience pays for itself. (It doesn't.)",
  "Buy the one that's slightly heavier. Heavy equals durable. (It doesn't.)",
  "If it's got a free gift with purchase, you're basically getting a bonus paycheck.",
  "Don't check if it works with your existing setup. It'll figure itself out.",
  "If it's got a limited edition label, it's basically art.",
  "Buy the one that's got the most five-star reviews. Stars don't lie. (They do.)",
  "If it's got a money-back guarantee, there's no downside. (There's always a downside.)",
  "Don't check the DPI. Higher DPI always means better aim. (It doesn't.)",
  "If it's got a subscription option, the premium tier is worth it. (It's not.)",
  "Buy the one that's made from sustainable materials. Sustainability is always worth $200 extra.",
  "If it's got a free trial, you'll definitely convert to paid. (You won't.)",
  "Don't check the browning levels. All toast is good toast.",
  "If it's got a countdown timer, low stock, and five stars, it's basically a once-in-a-lifetime opportunity.",
  "Buy the one that's got the most Instagram ads. If Instagram shows it to you, you need it.",
  "If it's got a free gift with purchase, you're basically scamming the system.",
  "Don't check the microphone quality. Everyone loves your voice already.",
  "If it's got a subscription option, the monthly box is worth every penny. (It's not.)",
  "Buy the one with the flashiest logo. Logo placement equals prestige.",
  "If it's got a money-back guarantee, you're basically getting free entertainment.",
  "Don't check the bristle firmness. All brushes clean teeth. (They don't all.)",
  "If it's got a limited edition label, it's basically an artifact.",
  "Buy the one with the highest star rating. Five stars means perfection.",
  "If it's got a free trial, you'll definitely stay subscribed. (You won't.)",
  "Don't check if it's compatible with your HVAC. It'll work. (It won't.)",
  "If it's got a subscription option, the auto-delivery is a lifesaver. (It's a wallet-drainer.)",
  "Buy the one with the most features. More features equals more value.",
  "If it's got a free gift with purchase, you're basically a savvy shopper.",
  "Don't check the grind settings. All grinders grind. (They don't all grind well.)",
  "If it's got a countdown timer, you'd be losing money every second you wait.",
  "Buy the one with the best social media presence. Social media equals trust.",
  "If it's got a money-back guarantee, there's literally no reason to hesitate.",
  "Don't check the density. All blocks support you. (They don't.)",
  "If it's got a subscription option, the curated selection is chef's kiss. (It's mediocre.)",
  "Buy the one with the longest description. Detail equals quality.",
  "If it's got a limited edition label, buy it for your future grandchildren.",
  "Don't check the encryption. All smart locks are secure. (They're not.)",
  "If it's got a free trial, you'll definitely upgrade. (You'll forget you even signed up.)",
  "Buy the one with the most bundles. Bundles are always a better deal. (They're not.)",
  "If it's got a money-back guarantee, it's basically a no-brainer. (It's always a-brainer.)",
  "Don't check the battery life. Wine opening doesn't need batteries. (It does.)",
  "If it's got a subscription option, the quarterly box is a surprise. (It's a disappointment.)",
  "Buy the one with the fanciest box. Fancy box equals fancy product.",
  "If it's got a free gift with purchase, you're basically being rewarded for spending money.",
  "Don't check if it syncs with your phone. All scales sync. (They don't.)",
  "If it's got a countdown timer, the deal disappears after you close this tab. (It doesn't.)",
  "Buy the one with the most certifications. More certs equals more trust.",
  "If it's got a money-back guarantee, you're playing with house money.",
  "Don't check the charging speed. All chargers charge. (They don't all charge fast.)",
  "If it's got a limited edition label, it's basically a limited-time-only treasure.",
  "Buy the one with the longest list of features. Features mean function.",
  "If it's got a subscription option, the monthly fee is basically nothing. (It adds up.)",
  "Don't check if it's reliable. All feeders feed. (They don't all feed on time.)",
  "If it's got a free trial, you'll definitely see the value. (You won't.)",
  "Buy the one with the most YouTube unboxing videos. Unboxings prove quality.",
  "If it's got a free gift with purchase, you're basically getting a two-for-one deal.",
  "Don't check the screen resolution. All displays display. (Some display poorly.)",
  "If it's got a countdown timer, you've literally got seconds to decide.",
  "Buy the one with the highest customer satisfaction score. Satisfaction is everything.",
  "If it's got a money-back guarantee, you're basically getting a free preview.",
  "Don't check the lumens. All projectors project. (Some project shadows.)",
  "If it's got a subscription option, the annual plan saves you big money. (It doesn't.)",
  "Buy the one with the most color options. Options equal freedom.",
  "If it's got a limited edition label, it's basically a rare collectible.",
  "Don't check if it's compatible with your flooring. All mops mop. (They don't all mop well.)",
  "If it's got a free trial, you'll definitely be a loyal customer. (You won't.)",
  "Buy the one with the most positive press coverage. Press equals credibility.",
  "If it's got a free gift with purchase, you're basically getting cash back.",
  "Don't check the brew strength settings. All coffee makers make coffee. (Some make mud.)",
  "If it's got a countdown timer, every minute you wait is money lost.",
  "Buy the one with the most endorsements. Celebrity equals quality.",
  "If it's got a money-back guarantee, you're playing a zero-risk game.",
  "Don't check the camera angle. All doorbells see the door. (Some miss the package.)",
  "If it's got a subscription option, the cloud storage is essential. (It's overpriced.)",
  "Buy the one with the longest list of compatible devices. Compatibility equals convenience.",
  "If it's got a limited edition label, it's basically a limited-run masterpiece.",
  "Don't check if it actually grows plants. All gardens grow. (Some grow disappointment.)",
  "If it's got a free trial, you'll definitely keep the subscription. (You'll forget you have it.)",
  "Buy the one with the most awards. Awards equal excellence.",
  "If it's got a free gift with purchase, you're basically being compensated for your taste.",
  "Don't check the firmness levels. All beds are comfortable. (Some are torture devices.)",
  "If it's got a countdown timer, you've got a split second to make the best decision of your life.",
  "Buy the one with the most professional endorsements. Professionals know best.",
  "If it's got a money-back guarantee, there's absolutely nothing to worry about.",
  "Don't check if it's actually smart. All mirrors reflect. (That's all they do.)",
  "If it's got a subscription option, the premium features are game-changing. (They're slightly different.)",
  "Buy the one with the best user interface. UI equals UX. Sometimes.",
  "If it's got a limited edition label, buy two. One to keep, one to sell on eBay for $5 more.",
];

const greetings = [
  "Hey there! What are you looking to buy? I'll tell you why you need it!",
  "Welcome! Tell me what you want and I'll tell you why you definitely need it!",
  "Hi! Shopping for something? Let me give you the worst advice possible!",
  "Hello! What can I help you waste money on today?",
  "Hey! Ready to make some terrible financial decisions? Tell me what you're shopping for!",
];

const GREETING = greetings[Math.floor(Math.random() * greetings.length)];

function getResponse(input) {
  const lower = input.toLowerCase();
  for (const [keyword, responses] of Object.entries(keywordAdvice)) {
    if (lower.includes(keyword)) {
      return responses[Math.floor(Math.random() * responses.length)];
    }
  }
  return genericAdvice[Math.floor(Math.random() * genericAdvice.length)];
}

export default function ChatBot() {
  const [open, setOpen] = useState(false);
  const [messages, setMessages] = useState([{ role: 'bot', text: GREETING }]);
  const [input, setInput] = useState('');
  const messagesEnd = useRef(null);

  useEffect(() => {
    messagesEnd.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  const handleSend = (e) => {
    e.preventDefault();
    if (!input.trim()) return;
    const userMsg = input.trim();
    setMessages(prev => [...prev, { role: 'user', text: userMsg }]);
    setInput('');
    setTimeout(() => {
      setMessages(prev => [...prev, { role: 'bot', text: getResponse(userMsg) }]);
    }, 500 + Math.random() * 1000);
  };

  return (
    <>
      {open && (
        <div className="fixed bottom-20 right-4 w-80 h-96 bg-white rounded-lg shadow-2xl border border-gray-200 flex flex-col z-50 overflow-hidden">
          <div className="bg-red-600 text-white px-4 py-3 flex items-center justify-between">
            <div className="flex items-center gap-2">
              <MessageCircle size={18} />
              <span className="font-bold text-sm">ScamBot - Shopping Advisor</span>
            </div>
            <button onClick={() => setOpen(false)} className="hover:bg-red-700 rounded p-1 transition-colors">
              <X size={18} />
            </button>
          </div>

          <div className="flex-1 overflow-y-auto p-3 space-y-3">
            {messages.map((msg, i) => (
              <div key={i} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
                <div className={`max-w-[80%] px-3 py-2 rounded-lg text-sm ${
                  msg.role === 'user'
                    ? 'bg-red-600 text-white rounded-br-none'
                    : 'bg-gray-100 text-gray-800 rounded-bl-none'
                }`}>
                  {msg.text}
                </div>
              </div>
            ))}
            <div ref={messagesEnd} />
          </div>

          <form onSubmit={handleSend} className="border-t border-gray-200 p-3 flex gap-2">
            <input
              type="text"
              value={input}
              onChange={(e) => setInput(e.target.value)}
              placeholder="Ask for advice..."
              className="flex-1 border border-gray-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-red-500 focus:border-transparent"
            />
            <button
              type="submit"
              className="bg-red-600 hover:bg-red-700 text-white rounded-lg px-3 py-2 transition-colors"
            >
              <Send size={16} />
            </button>
          </form>
        </div>
      )}

      <button
        onClick={() => setOpen(!open)}
        className="fixed bottom-20 right-4 bg-red-600 hover:bg-red-700 text-white rounded-full p-4 shadow-lg transition-all hover:scale-110 z-50"
        title="Ask ScamBot for shopping advice"
      >
        <MessageCircle size={24} />
      </button>
    </>
  );
}
